### ISSUE TITLE
2.5.4: Invalid data on RAWv1

### ISSUE THREAD

**Issue by ojousima** [ruuvi/ruuvitag_fw#156]

**Comment by DG12** [comment]
Rather than INVALID do you mean UNAVAILABLE ?

**Comment by ojousima** [comment]
I mean encoded wrong. Something broke when supporting the unavailable data for RAWv2, target is to fix it on 2019-09-04

**Comment by DG12** [comment]
Regarding INVALID constants:
Rather than INVALID do you mean UNAVAILABLE ?

Although it does not make much difference,
you might consider using  more integer friendly values for example:
TEMPERATURE_UNAVAILABLE 126  // max is 85C , 126 is a small positive integer
HUMIDITY_UNAVAILABLE   126 // max is 100%, 126 is a small positive integer
PRESSURE_UNAVAILABLE  1101 // max is 1100
ACCELERATION_UNAVAILABLE 16001 // max per data sheet is 16000

Just a thought.

This code seems to imply that there may be ruuuviTags without either temperature/pressure/humidity or acceleration sensors or both.
